In [1]:
import os
import warnings
import tqdm
import pandas as pd
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)

In [2]:
%load_ext autoreload
%autoreload 2
import socceraction.vaep.features as fs
import socceraction.vaep.labels as lab

In [3]:
datafolder = "../data-fifa"
spadl_h5 = os.path.join(datafolder, "spadl-statsbomb.h5")
features_h5 = os.path.join(datafolder, "features.h5")
labels_h5 = os.path.join(datafolder, "labels.h5")
predictions_h5 = os.path.join(datafolder, "predictions.h5")

In [4]:
games = pd.read_hdf(spadl_h5, "games")
print("nb of games:", len(games))

# note: only for the purpose of this example and due to the small dataset,
# we use the same data for training and evaluation
traingames = games
testgames = games

nb of games: 64

In [5]:
testgames

,game_id,season_id,competition_id,competition_stage,game_day,game_date,home_team_id,away_team_id,home_score,away_score,venue,referee,competition_name,country_name,competition_gender,season_name,home_team_name,away_team_name
0,7548,3,43,Group Stage,2,2018-06-22 14:00:00,781,795,2,0,Saint-Petersburg Stadium,Björn Kuipers,FIFA World Cup,International,male,2018,Brazil,Costa Rica
1,7578,3,43,Group Stage,1,2018-06-15 14:00:00,774,783,0,1,\tEkaterinburg Arena,Björn Kuipers,FIFA World Cup,International,male,2018,Egypt,Uruguay
2,7553,3,43,Group Stage,2,2018-06-23 17:00:00,791,794,1,2,\tRostov Arena,Milorad Mažić,FIFA World Cup,International,male,2018,South Korea,Mexico
3,7544,3,43,Group Stage,2,2018-06-20 17:00:00,783,799,1,0,\tRostov Arena,Clément Turpin,FIFA World Cup,International,male,2018,Uruguay,Saudi Arabia
4,7536,3,43,Group Stage,1,2018-06-18 17:00:00,782,798,3,0,\tOlimpiyskiy Stadion Fisht,Janny Sikazwe,FIFA World Cup,International,male,2018,Belgium,Panama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,7540,3,43,Group Stage,2,2018-06-19 20:00:00,796,774,3,1,Saint-Petersburg Stadium,Enrique Cáceres,FIFA World Cup,International,male,2018,Russia,Egypt
60,8652,3,43,Quarter-finals,5,2018-07-07 20:00:00,796,785,2,2,\tOlimpiyskiy Stadion Fisht,Sandro Ricci,FIFA World Cup,International,male,2018,Russia,Croatia
61,7563,3,43,Group Stage,3,2018-06-26 16:00:00,776,771,0,0,Stadion Luzhniki,Sandro Ricci,FIFA World Cup,International,male,2018,Denmark,France
62,7556,3,43,Group Stage,2,2018-06-24 17:00:00,778,787,2,2,\tEkaterinburg Arena,Gianluca Rocchi,FIFA World Cup,International,male,2018,Japan,Senegal
63,7559,3,43,Group Stage,3,2018-06-25 16:00:00,799,774,2,1,Volgograd Arena,Wilmar Alexander Roldán Pérez,FIFA World Cup,International,male,2018,Saudi Arabia,Egypt

In [6]:
# 1. Select feature set X
xfns = [
    fs.actiontype,
    fs.actiontype_onehot,
    #fs.bodypart,
    fs.bodypart_onehot,
    fs.result,
    fs.result_onehot,
    fs.goalscore,
    fs.startlocation,
    fs.endlocation,
    fs.movement,
    fs.space_delta,
    fs.startpolar,
    fs.endpolar,
    fs.team,
    #fs.time,
    fs.time_delta,
    #fs.actiontype_result_onehot
]
nb_prev_actions = 3

Xcols = fs.feature_column_names(xfns, nb_prev_actions)

def getXY(games,Xcols):
    # generate the columns of the selected feature
    X = []
    for game_id in tqdm.tqdm(games.game_id, desc="Selecting features"):
        Xi = pd.read_hdf(features_h5, f"game_{game_id}")
        X.append(Xi[Xcols])
    X = pd.concat(X).reset_index(drop=True)

    # 2. Select label Y
    Ycols = ["scores","concedes"]
    Y = []
    for game_id in tqdm.tqdm(games.game_id, desc="Selecting label"):
        Yi = pd.read_hdf(labels_h5, f"game_{game_id}")
        Y.append(Yi[Ycols])
    Y = pd.concat(Y).reset_index(drop=True)
    return X, Y

X, Y = getXY(traingames,Xcols)
print("X:", list(X.columns))
print("Y:", list(Y.columns))

Selecting features: 100%|██████████| 64/64 [00:00<00:00, 84.25it/s]
Selecting label: 100%|██████████| 64/64 [00:00<00:00, 220.02it/s]

X: ['type_id_a0', 'type_id_a1', 'type_id_a2', 'type_pass_a0', 'type_cross_a0', 'type_throw_in_a0', 'type_freekick_crossed_a0', 'type_freekick_short_a0', 'type_corner_crossed_a0', 'type_corner_short_a0', 'type_take_on_a0', 'type_foul_a0', 'type_tackle_a0', 'type_interception_a0', 'type_shot_a0', 'type_shot_penalty_a0', 'type_shot_freekick_a0', 'type_keeper_save_a0', 'type_keeper_claim_a0', 'type_keeper_punch_a0', 'type_keeper_pick_up_a0', 'type_clearance_a0', 'type_bad_touch_a0', 'type_non_action_a0', 'type_dribble_a0', 'type_goalkick_a0', 'type_pass_a1', 'type_cross_a1', 'type_throw_in_a1', 'type_freekick_crossed_a1', 'type_freekick_short_a1', 'type_corner_crossed_a1', 'type_corner_short_a1', 'type_take_on_a1', 'type_foul_a1', 'type_tackle_a1', 'type_interception_a1', 'type_shot_a1', 'type_shot_penalty_a1', 'type_shot_freekick_a1', 'type_keeper_save_a1', 'type_keeper_claim_a1', 'type_keeper_punch_a1', 'type_keeper_pick_up_a1', 'type_clearance_a1', 'type_bad_touch_a1', 'type_non_action_a1', 'type_dribble_a1', 'type_goalkick_a1', 'type_pass_a2', 'type_cross_a2', 'type_throw_in_a2', 'type_freekick_crossed_a2', 'type_freekick_short_a2', 'type_corner_crossed_a2', 'type_corner_short_a2', 'type_take_on_a2', 'type_foul_a2', 'type_tackle_a2', 'type_interception_a2', 'type_shot_a2', 'type_shot_penalty_a2', 'type_shot_freekick_a2', 'type_keeper_save_a2', 'type_keeper_claim_a2', 'type_keeper_punch_a2', 'type_keeper_pick_up_a2', 'type_clearance_a2', 'type_bad_touch_a2', 'type_non_action_a2', 'type_dribble_a2', 'type_goalkick_a2', 'bodypart_foot_a0', 'bodypart_head_a0', 'bodypart_other_a0', 'bodypart_head/other_a0', 'bodypart_foot_a1', 'bodypart_head_a1', 'bodypart_other_a1', 'bodypart_head/other_a1', 'bodypart_foot_a2', 'bodypart_head_a2', 'bodypart_other_a2', 'bodypart_head/other_a2', 'result_id_a0', 'result_id_a1', 'result_id_a2', 'result_fail_a0', 'result_success_a0', 'result_offside_a0', 'result_owngoal_a0', 'result_yellow_card_a0', 'result_red_card_a0', 'result_fail_a1', 'result_success_a1', 'result_offside_a1', 'result_owngoal_a1', 'result_yellow_card_a1', 'result_red_card_a1', 'result_fail_a2', 'result_success_a2', 'result_offside_a2', 'result_owngoal_a2', 'result_yellow_card_a2', 'result_red_card_a2', 'goalscore_team', 'goalscore_opponent', 'goalscore_diff', 'start_x_a0', 'start_y_a0', 'start_x_a1', 'start_y_a1', 'start_x_a2', 'start_y_a2', 'end_x_a0', 'end_y_a0', 'end_x_a1', 'end_y_a1', 'end_x_a2', 'end_y_a2', 'dx_a0', 'dy_a0', 'movement_a0', 'dx_a1', 'dy_a1', 'movement_a1', 'dx_a2', 'dy_a2', 'movement_a2', 'dx_a01', 'dy_a01', 'mov_a01', 'dx_a02', 'dy_a02', 'mov_a02', 'start_dist_to_goal_a0', 'start_angle_to_goal_a0', 'start_dist_to_goal_a1', 'start_angle_to_goal_a1', 'start_dist_to_goal_a2', 'start_angle_to_goal_a2', 'end_dist_to_goal_a0', 'end_angle_to_goal_a0', 'end_dist_to_goal_a1', 'end_angle_to_goal_a1', 'end_dist_to_goal_a2', 'end_angle_to_goal_a2', 'team_1', 'team_2', 'time_delta_1', 'time_delta_2']
Y: ['scores', 'concedes']

In [7]:
X.shape,Y.shape

((128937, 151), (128937, 2))

In [8]:
X

,type_id_a0,type_id_a1,type_id_a2,type_pass_a0,type_cross_a0,type_throw_in_a0,type_freekick_crossed_a0,type_freekick_short_a0,type_corner_crossed_a0,type_corner_short_a0,...,end_dist_to_goal_a0,end_angle_to_goal_a0,end_dist_to_goal_a1,end_angle_to_goal_a1,end_dist_to_goal_a2,end_angle_to_goal_a2,team_1,team_2,time_delta_1,time_delta_2
0,0,0,0,True,False,False,False,False,False,False,...,87.354001,0.004927,87.354001,0.004927,87.354001,0.004927,True,True,0.0,0.0
1,21,0,0,False,False,False,False,False,False,False,...,84.838075,0.055832,87.354001,0.004927,87.354001,0.004927,True,True,2.0,2.0
2,0,21,0,True,False,False,False,False,False,False,...,32.550722,0.572928,84.838075,0.055832,87.354001,0.004927,True,True,2.0,4.0
3,0,0,21,True,False,False,False,False,False,False,...,76.671868,0.209214,79.626829,0.223458,20.838993,0.229180,False,False,3.0,5.0
4,21,0,0,False,False,False,False,False,False,False,...,75.023036,0.155515,76.671868,0.209214,79.626829,0.223458,True,False,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128932,0,9,7,True,False,False,False,False,False,False,...,13.863228,0.795235,16.142562,1.406072,16.142562,1.406072,False,True,2.0,2.0
128933,21,0,9,False,False,False,False,False,False,False,...,15.727082,0.753421,13.863228,0.795235,16.142562,1.406072,True,False,1.0,3.0
128934,0,21,0,True,False,False,False,False,False,False,...,11.628859,1.181669,15.727082,0.753421,13.863228,0.795235,True,True,0.0,1.0
128935,11,0,21,False,False,False,False,False,False,False,...,3.529114,1.570796,11.628859,1.181669,15.727082,0.753421,True,True,1.0,1.0
128936,0,11,0,True,False,False,False,False,False,False,...,61.778199,0.020901,105.059291,0.033598,101.162047,0.106561,False,False,83.0,84.0

In [9]:
Y

        scores  concedes
0        False     False
1        False     False
2        False     False
3        False     False
4        False     False
...        ...       ...
128932    True     False
128933    True     False
128934    True     False
128935    True     False
128936   False     False

[128937 rows x 2 columns]

In [22]:
# 3. train classifiers F(X) = Y
import xgboost
import catboost
Y_hat = pd.DataFrame()
models = {}
for col in list(Y.columns):
    model = catboost.CatBoostClassifier()
    model.fit(X, Y[col])
    models[col] = model
model

Learning rate set to 0.082047
0:	learn: 0.5225217	total: 156ms	remaining: 2m 35s
1:	learn: 0.4007154	total: 178ms	remaining: 1m 28s
2:	learn: 0.3096112	total: 199ms	remaining: 1m 6s
3:	learn: 0.2394887	total: 220ms	remaining: 54.7s
4:	learn: 0.1883602	total: 242ms	remaining: 48.1s
5:	learn: 0.1530675	total: 272ms	remaining: 45s
6:	learn: 0.1281892	total: 298ms	remaining: 42.3s
7:	learn: 0.1098956	total: 325ms	remaining: 40.3s
8:	learn: 0.0956320	total: 348ms	remaining: 38.3s
9:	learn: 0.0857088	total: 374ms	remaining: 37s
10:	learn: 0.0772978	total: 399ms	remaining: 35.9s
11:	learn: 0.0710094	total: 423ms	remaining: 34.8s
12:	learn: 0.0658546	total: 445ms	remaining: 33.8s
13:	learn: 0.0618745	total: 466ms	remaining: 32.8s
14:	learn: 0.0589968	total: 488ms	remaining: 32s
15:	learn: 0.0565342	total: 509ms	remaining: 31.3s
16:	learn: 0.0543457	total: 530ms	remaining: 30.6s
17:	learn: 0.0527572	total: 550ms	remaining: 30s
18:	learn: 0.0516389	total: 572ms	remaining: 29.5s
19:	learn: 0.0506812	total: 593ms	remaining: 29.1s
20:	learn: 0.0497334	total: 619ms	remaining: 28.8s
21:	learn: 0.0490303	total: 645ms	remaining: 28.7s
22:	learn: 0.0484149	total: 673ms	remaining: 28.6s
23:	learn: 0.0479077	total: 698ms	remaining: 28.4s
24:	learn: 0.0476219	total: 722ms	remaining: 28.2s
25:	learn: 0.0472345	total: 745ms	remaining: 27.9s
26:	learn: 0.0468962	total: 766ms	remaining: 27.6s
27:	learn: 0.0465201	total: 790ms	remaining: 27.4s
28:	learn: 0.0462609	total: 811ms	remaining: 27.2s
29:	learn: 0.0460623	total: 830ms	remaining: 26.9s
30:	learn: 0.0458731	total: 854ms	remaining: 26.7s
31:	learn: 0.0456817	total: 878ms	remaining: 26.6s
32:	learn: 0.0455548	total: 908ms	remaining: 26.6s
33:	learn: 0.0454311	total: 926ms	remaining: 26.3s
34:	learn: 0.0452765	total: 945ms	remaining: 26.1s
35:	learn: 0.0451559	total: 963ms	remaining: 25.8s
36:	learn: 0.0450079	total: 983ms	remaining: 25.6s
37:	learn: 0.0449072	total: 1s	remaining: 25.4s
38:	learn: 0.0448133	total: 1.03s	remaining: 25.5s
39:	learn: 0.0447612	total: 1.05s	remaining: 25.3s
40:	learn: 0.0446881	total: 1.07s	remaining: 25.1s
41:	learn: 0.0446434	total: 1.09s	remaining: 25s
42:	learn: 0.0445889	total: 1.11s	remaining: 24.8s
43:	learn: 0.0445566	total: 1.13s	remaining: 24.6s
44:	learn: 0.0444319	total: 1.15s	remaining: 24.5s
45:	learn: 0.0443851	total: 1.17s	remaining: 24.3s
46:	learn: 0.0443212	total: 1.19s	remaining: 24.1s
47:	learn: 0.0442734	total: 1.21s	remaining: 24s
48:	learn: 0.0442136	total: 1.23s	remaining: 23.9s
49:	learn: 0.0441652	total: 1.25s	remaining: 23.8s
50:	learn: 0.0441260	total: 1.27s	remaining: 23.6s
51:	learn: 0.0440909	total: 1.29s	remaining: 23.5s
52:	learn: 0.0440542	total: 1.31s	remaining: 23.4s
53:	learn: 0.0440130	total: 1.33s	remaining: 23.3s
54:	learn: 0.0439431	total: 1.35s	remaining: 23.2s
55:	learn: 0.0438940	total: 1.37s	remaining: 23.2s
56:	learn: 0.0438465	total: 1.39s	remaining: 23s
57:	learn: 0.0437761	total: 1.41s	remaining: 23s
58:	learn: 0.0437265	total: 1.43s	remaining: 22.9s
59:	learn: 0.0436969	total: 1.46s	remaining: 22.8s
60:	learn: 0.0436677	total: 1.47s	remaining: 22.7s
61:	learn: 0.0436271	total: 1.49s	remaining: 22.6s
62:	learn: 0.0435748	total: 1.52s	remaining: 22.6s
63:	learn: 0.0435563	total: 1.54s	remaining: 22.5s
64:	learn: 0.0434929	total: 1.56s	remaining: 22.4s
65:	learn: 0.0434697	total: 1.58s	remaining: 22.3s
66:	learn: 0.0434496	total: 1.6s	remaining: 22.3s
67:	learn: 0.0434365	total: 1.62s	remaining: 22.2s
68:	learn: 0.0433775	total: 1.64s	remaining: 22.1s
69:	learn: 0.0433437	total: 1.66s	remaining: 22s
70:	learn: 0.0433207	total: 1.68s	remaining: 21.9s
71:	learn: 0.0433072	total: 1.7s	remaining: 21.9s
72:	learn: 0.0432608	total: 1.72s	remaining: 21.8s
73:	learn: 0.0432377	total: 1.74s	remaining: 21.8s
74:	learn: 0.0432181	total: 1.76s	remaining: 21.7s
75:	learn: 0.0431920	total: 1.78s	remaining: 21.6s
76:	learn: 0.0431777	total: 1.8s	remaining: 21.5s
77:	learn: 0.0431640	total: 1.81s	remaining: 21.5s
78:	learn: 0.0431346	total: 1.83s	remaining: 21.4s
79:	learn: 0.0430775	total: 1.85s	remaining: 21.3s
80:	learn: 0.0430677	total: 1.87s	remaining: 21.2s
81:	learn: 0.0430393	total: 1.89s	remaining: 21.2s
82:	learn: 0.0429992	total: 1.91s	remaining: 21.1s
83:	learn: 0.0429671	total: 1.93s	remaining: 21.1s
84:	learn: 0.0429495	total: 1.95s	remaining: 21s
85:	learn: 0.0429129	total: 1.97s	remaining: 21s
86:	learn: 0.0428920	total: 1.99s	remaining: 20.9s
87:	learn: 0.0428553	total: 2.01s	remaining: 20.8s
88:	learn: 0.0428306	total: 2.03s	remaining: 20.8s
89:	learn: 0.0427950	total: 2.05s	remaining: 20.7s
90:	learn: 0.0427760	total: 2.07s	remaining: 20.7s
91:	learn: 0.0427513	total: 2.09s	remaining: 20.6s
92:	learn: 0.0427146	total: 2.11s	remaining: 20.6s
93:	learn: 0.0426616	total: 2.13s	remaining: 20.5s
94:	learn: 0.0426418	total: 2.15s	remaining: 20.5s
95:	learn: 0.0426087	total: 2.17s	remaining: 20.5s
96:	learn: 0.0425797	total: 2.19s	remaining: 20.4s
97:	learn: 0.0425303	total: 2.21s	remaining: 20.4s
98:	learn: 0.0425049	total: 2.23s	remaining: 20.3s
99:	learn: 0.0424843	total: 2.25s	remaining: 20.2s
100:	learn: 0.0424498	total: 2.27s	remaining: 20.2s
101:	learn: 0.0424244	total: 2.29s	remaining: 20.2s
102:	learn: 0.0423767	total: 2.31s	remaining: 20.1s
103:	learn: 0.0423529	total: 2.33s	remaining: 20.1s
104:	learn: 0.0423300	total: 2.35s	remaining: 20s
105:	learn: 0.0423134	total: 2.37s	remaining: 20s
106:	learn: 0.0422753	total: 2.39s	remaining: 20s
107:	learn: 0.0422646	total: 2.41s	remaining: 19.9s
108:	learn: 0.0422380	total: 2.43s	remaining: 19.9s
109:	learn: 0.0422111	total: 2.45s	remaining: 19.8s
110:	learn: 0.0421752	total: 2.47s	remaining: 19.8s
111:	learn: 0.0421437	total: 2.49s	remaining: 19.7s
112:	learn: 0.0421181	total: 2.51s	remaining: 19.7s
113:	learn: 0.0421018	total: 2.53s	remaining: 19.6s
114:	learn: 0.0420711	total: 2.55s	remaining: 19.6s
115:	learn: 0.0420564	total: 2.56s	remaining: 19.5s
116:	learn: 0.0420164	total: 2.58s	remaining: 19.5s
117:	learn: 0.0420067	total: 2.61s	remaining: 19.5s
118:	learn: 0.0419947	total: 2.63s	remaining: 19.4s
119:	learn: 0.0419705	total: 2.65s	remaining: 19.4s
120:	learn: 0.0419381	total: 2.67s	remaining: 19.4s
121:	learn: 0.0419245	total: 2.69s	remaining: 19.3s
122:	learn: 0.0419028	total: 2.71s	remaining: 19.3s
123:	learn: 0.0418817	total: 2.72s	remaining: 19.2s
124:	learn: 0.0418467	total: 2.74s	remaining: 19.2s
125:	learn: 0.0418134	total: 2.76s	remaining: 19.2s
126:	learn: 0.0417792	total: 2.78s	remaining: 19.1s
127:	learn: 0.0417645	total: 2.8s	remaining: 19.1s
128:	learn: 0.0417507	total: 2.82s	remaining: 19.1s
129:	learn: 0.0416977	total: 2.84s	remaining: 19s
130:	learn: 0.0416856	total: 2.86s	remaining: 19s
131:	learn: 0.0416679	total: 2.88s	remaining: 18.9s
132:	learn: 0.0416509	total: 2.9s	remaining: 18.9s
133:	learn: 0.0416129	total: 2.92s	remaining: 18.9s
134:	learn: 0.0415776	total: 2.95s	remaining: 18.9s
135:	learn: 0.0415483	total: 2.97s	remaining: 18.9s
136:	learn: 0.0415343	total: 2.99s	remaining: 18.9s
137:	learn: 0.0415137	total: 3.02s	remaining: 18.8s
138:	learn: 0.0415047	total: 3.04s	remaining: 18.8s
139:	learn: 0.0414878	total: 3.06s	remaining: 18.8s
140:	learn: 0.0414660	total: 3.08s	remaining: 18.7s
141:	learn: 0.0414323	total: 3.1s	remaining: 18.7s
142:	learn: 0.0413994	total: 3.11s	remaining: 18.7s
143:	learn: 0.0413835	total: 3.13s	remaining: 18.6s
144:	learn: 0.0413216	total: 3.15s	remaining: 18.6s
145:	learn: 0.0413021	total: 3.17s	remaining: 18.5s
146:	learn: 0.0412888	total: 3.19s	remaining: 18.5s
147:	learn: 0.0412577	total: 3.21s	remaining: 18.5s
148:	learn: 0.0412363	total: 3.23s	remaining: 18.5s
149:	learn: 0.0412230	total: 3.25s	remaining: 18.4s
150:	learn: 0.0412087	total: 3.27s	remaining: 18.4s
151:	learn: 0.0411975	total: 3.29s	remaining: 18.4s
152:	learn: 0.0411832	total: 3.31s	remaining: 18.4s
153:	learn: 0.0411717	total: 3.34s	remaining: 18.3s
154:	learn: 0.0411351	total: 3.36s	remaining: 18.3s
155:	learn: 0.0410940	total: 3.38s	remaining: 18.3s
156:	learn: 0.0410687	total: 3.45s	remaining: 18.5s
157:	learn: 0.0410622	total: 3.47s	remaining: 18.5s
158:	learn: 0.0410419	total: 3.5s	remaining: 18.5s
159:	learn: 0.0410292	total: 3.52s	remaining: 18.5s
160:	learn: 0.0410176	total: 3.54s	remaining: 18.4s
161:	learn: 0.0410066	total: 3.56s	remaining: 18.4s
162:	learn: 0.0410025	total: 3.58s	remaining: 18.4s
163:	learn: 0.0409910	total: 3.6s	remaining: 18.3s
164:	learn: 0.0409406	total: 3.62s	remaining: 18.3s
165:	learn: 0.0409299	total: 3.64s	remaining: 18.3s
166:	learn: 0.0409155	total: 3.66s	remaining: 18.2s
167:	learn: 0.0409033	total: 3.68s	remaining: 18.2s
168:	learn: 0.0408800	total: 3.7s	remaining: 18.2s
169:	learn: 0.0408705	total: 3.71s	remaining: 18.1s
170:	learn: 0.0408580	total: 3.73s	remaining: 18.1s
171:	learn: 0.0408446	total: 3.75s	remaining: 18.1s
172:	learn: 0.0408288	total: 3.77s	remaining: 18s
173:	learn: 0.0408246	total: 3.79s	remaining: 18s
174:	learn: 0.0408150	total: 3.81s	remaining: 18s
175:	learn: 0.0408091	total: 3.83s	remaining: 17.9s
176:	learn: 0.0407772	total: 3.85s	remaining: 17.9s
177:	learn: 0.0407676	total: 3.86s	remaining: 17.8s
178:	learn: 0.0407428	total: 3.88s	remaining: 17.8s
179:	learn: 0.0407303	total: 3.9s	remaining: 17.8s
180:	learn: 0.0407217	total: 3.92s	remaining: 17.7s
181:	learn: 0.0407129	total: 3.94s	remaining: 17.7s
182:	learn: 0.0406754	total: 3.96s	remaining: 17.7s
183:	learn: 0.0406693	total: 3.98s	remaining: 17.6s
184:	learn: 0.0406359	total: 4s	remaining: 17.6s
185:	learn: 0.0406044	total: 4.02s	remaining: 17.6s
186:	learn: 0.0405956	total: 4.03s	remaining: 17.5s
187:	learn: 0.0405892	total: 4.05s	remaining: 17.5s
188:	learn: 0.0405682	total: 4.07s	remaining: 17.5s
189:	learn: 0.0405572	total: 4.09s	remaining: 17.4s
190:	learn: 0.0405539	total: 4.11s	remaining: 17.4s
191:	learn: 0.0405439	total: 4.13s	remaining: 17.4s
192:	learn: 0.0405345	total: 4.15s	remaining: 17.3s
193:	learn: 0.0405288	total: 4.17s	remaining: 17.3s
194:	learn: 0.0404883	total: 4.18s	remaining: 17.3s
195:	learn: 0.0404600	total: 4.2s	remaining: 17.2s
196:	learn: 0.0404379	total: 4.22s	remaining: 17.2s
197:	learn: 0.0404277	total: 4.24s	remaining: 17.2s
198:	learn: 0.0403806	total: 4.26s	remaining: 17.2s
199:	learn: 0.0403732	total: 4.28s	remaining: 17.1s
200:	learn: 0.0403543	total: 4.3s	remaining: 17.1s
201:	learn: 0.0403416	total: 4.32s	remaining: 17.1s
202:	learn: 0.0403351	total: 4.34s	remaining: 17s
203:	learn: 0.0403276	total: 4.35s	remaining: 17s
204:	learn: 0.0403061	total: 4.37s	remaining: 17s
205:	learn: 0.0402994	total: 4.39s	remaining: 16.9s
206:	learn: 0.0402910	total: 4.41s	remaining: 16.9s
207:	learn: 0.0402890	total: 4.42s	remaining: 16.8s
208:	learn: 0.0402858	total: 4.45s	remaining: 16.8s
209:	learn: 0.0402831	total: 4.46s	remaining: 16.8s
210:	learn: 0.0402417	total: 4.48s	remaining: 16.8s
211:	learn: 0.0402345	total: 4.5s	remaining: 16.7s
212:	learn: 0.0402002	total: 4.52s	remaining: 16.7s
213:	learn: 0.0401724	total: 4.54s	remaining: 16.7s
214:	learn: 0.0401291	total: 4.56s	remaining: 16.6s
215:	learn: 0.0401215	total: 4.58s	remaining: 16.6s
216:	learn: 0.0401107	total: 4.59s	remaining: 16.6s
217:	learn: 0.0400847	total: 4.61s	remaining: 16.5s
218:	learn: 0.0400778	total: 4.63s	remaining: 16.5s
219:	learn: 0.0400708	total: 4.65s	remaining: 16.5s
220:	learn: 0.0400621	total: 4.67s	remaining: 16.4s
221:	learn: 0.0400562	total: 4.69s	remaining: 16.4s
222:	learn: 0.0400192	total: 4.71s	remaining: 16.4s
223:	learn: 0.0400163	total: 4.72s	remaining: 16.4s
224:	learn: 0.0399981	total: 4.74s	remaining: 16.3s
225:	learn: 0.0399901	total: 4.76s	remaining: 16.3s
226:	learn: 0.0399751	total: 4.78s	remaining: 16.3s
227:	learn: 0.0399672	total: 4.8s	remaining: 16.3s
228:	learn: 0.0399605	total: 4.82s	remaining: 16.2s
229:	learn: 0.0399518	total: 4.83s	remaining: 16.2s
230:	learn: 0.0399308	total: 4.85s	remaining: 16.2s
231:	learn: 0.0399209	total: 4.87s	remaining: 16.1s
232:	learn: 0.0398843	total: 4.89s	remaining: 16.1s
233:	learn: 0.0398638	total: 4.91s	remaining: 16.1s
234:	learn: 0.0398220	total: 4.93s	remaining: 16.1s
235:	learn: 0.0397803	total: 4.95s	remaining: 16s
236:	learn: 0.0397329	total: 4.97s	remaining: 16s
237:	learn: 0.0397188	total: 4.99s	remaining: 16s
238:	learn: 0.0397157	total: 5.01s	remaining: 16s
239:	learn: 0.0396854	total: 5.03s	remaining: 15.9s
240:	learn: 0.0396558	total: 5.05s	remaining: 15.9s
241:	learn: 0.0396457	total: 5.07s	remaining: 15.9s
242:	learn: 0.0396218	total: 5.09s	remaining: 15.8s
243:	learn: 0.0396075	total: 5.1s	remaining: 15.8s
244:	learn: 0.0395884	total: 5.12s	remaining: 15.8s
245:	learn: 0.0395812	total: 5.14s	remaining: 15.8s
246:	learn: 0.0395771	total: 5.16s	remaining: 15.7s
247:	learn: 0.0395710	total: 5.17s	remaining: 15.7s
248:	learn: 0.0395670	total: 5.2s	remaining: 15.7s
249:	learn: 0.0395595	total: 5.22s	remaining: 15.6s
250:	learn: 0.0395526	total: 5.24s	remaining: 15.6s
251:	learn: 0.0395445	total: 5.26s	remaining: 15.6s
252:	learn: 0.0395410	total: 5.28s	remaining: 15.6s
253:	learn: 0.0395371	total: 5.3s	remaining: 15.6s
254:	learn: 0.0395202	total: 5.32s	remaining: 15.5s
255:	learn: 0.0395027	total: 5.34s	remaining: 15.5s
256:	learn: 0.0394864	total: 5.36s	remaining: 15.5s
257:	learn: 0.0394856	total: 5.37s	remaining: 15.5s
258:	learn: 0.0394789	total: 5.39s	remaining: 15.4s
259:	learn: 0.0394523	total: 5.42s	remaining: 15.4s
260:	learn: 0.0394503	total: 5.44s	remaining: 15.4s
261:	learn: 0.0394421	total: 5.46s	remaining: 15.4s
262:	learn: 0.0394277	total: 5.47s	remaining: 15.3s
263:	learn: 0.0394056	total: 5.5s	remaining: 15.3s
264:	learn: 0.0393847	total: 5.52s	remaining: 15.3s
265:	learn: 0.0393537	total: 5.54s	remaining: 15.3s
266:	learn: 0.0393496	total: 5.55s	remaining: 15.2s
267:	learn: 0.0393348	total: 5.57s	remaining: 15.2s
268:	learn: 0.0393228	total: 5.59s	remaining: 15.2s
269:	learn: 0.0393019	total: 5.61s	remaining: 15.2s
270:	learn: 0.0392980	total: 5.63s	remaining: 15.1s
271:	learn: 0.0392865	total: 5.65s	remaining: 15.1s
272:	learn: 0.0392366	total: 5.67s	remaining: 15.1s
273:	learn: 0.0392265	total: 5.7s	remaining: 15.1s
274:	learn: 0.0392156	total: 5.72s	remaining: 15.1s
275:	learn: 0.0392052	total: 5.74s	remaining: 15.1s
276:	learn: 0.0392021	total: 5.75s	remaining: 15s
277:	learn: 0.0391812	total: 5.78s	remaining: 15s
278:	learn: 0.0391692	total: 5.8s	remaining: 15s
279:	learn: 0.0391426	total: 5.82s	remaining: 15s
280:	learn: 0.0391300	total: 5.84s	remaining: 14.9s
281:	learn: 0.0390959	total: 5.86s	remaining: 14.9s
282:	learn: 0.0390865	total: 5.88s	remaining: 14.9s
283:	learn: 0.0390468	total: 5.9s	remaining: 14.9s
284:	learn: 0.0390252	total: 5.92s	remaining: 14.8s
285:	learn: 0.0389997	total: 5.94s	remaining: 14.8s
286:	learn: 0.0389697	total: 5.96s	remaining: 14.8s
287:	learn: 0.0389571	total: 5.98s	remaining: 14.8s
288:	learn: 0.0389476	total: 6s	remaining: 14.8s
289:	learn: 0.0389423	total: 6.02s	remaining: 14.7s
290:	learn: 0.0389343	total: 6.03s	remaining: 14.7s
291:	learn: 0.0388861	total: 6.05s	remaining: 14.7s
292:	learn: 0.0388823	total: 6.07s	remaining: 14.7s
293:	learn: 0.0388509	total: 6.09s	remaining: 14.6s
294:	learn: 0.0388326	total: 6.11s	remaining: 14.6s
295:	learn: 0.0388319	total: 6.13s	remaining: 14.6s
296:	learn: 0.0388264	total: 6.15s	remaining: 14.6s
297:	learn: 0.0387908	total: 6.17s	remaining: 14.5s
298:	learn: 0.0387795	total: 6.19s	remaining: 14.5s
299:	learn: 0.0387580	total: 6.21s	remaining: 14.5s
300:	learn: 0.0387368	total: 6.23s	remaining: 14.5s
301:	learn: 0.0386951	total: 6.25s	remaining: 14.4s
302:	learn: 0.0386754	total: 6.27s	remaining: 14.4s
303:	learn: 0.0386708	total: 6.29s	remaining: 14.4s
304:	learn: 0.0386675	total: 6.31s	remaining: 14.4s
305:	learn: 0.0386625	total: 6.33s	remaining: 14.4s
306:	learn: 0.0386545	total: 6.35s	remaining: 14.3s
307:	learn: 0.0386438	total: 6.37s	remaining: 14.3s
308:	learn: 0.0386410	total: 6.39s	remaining: 14.3s
309:	learn: 0.0386213	total: 6.41s	remaining: 14.3s
310:	learn: 0.0386044	total: 6.43s	remaining: 14.2s
311:	learn: 0.0385941	total: 6.45s	remaining: 14.2s
312:	learn: 0.0385826	total: 6.47s	remaining: 14.2s
313:	learn: 0.0385726	total: 6.49s	remaining: 14.2s
314:	learn: 0.0385693	total: 6.51s	remaining: 14.2s
315:	learn: 0.0385652	total: 6.53s	remaining: 14.1s
316:	learn: 0.0385580	total: 6.55s	remaining: 14.1s
317:	learn: 0.0385557	total: 6.56s	remaining: 14.1s
318:	learn: 0.0385450	total: 6.58s	remaining: 14.1s
319:	learn: 0.0385422	total: 6.6s	remaining: 14s
320:	learn: 0.0385353	total: 6.62s	remaining: 14s
321:	learn: 0.0384984	total: 6.64s	remaining: 14s
322:	learn: 0.0384887	total: 6.66s	remaining: 14s
323:	learn: 0.0384775	total: 6.68s	remaining: 13.9s
324:	learn: 0.0384554	total: 6.7s	remaining: 13.9s
325:	learn: 0.0384423	total: 6.71s	remaining: 13.9s
326:	learn: 0.0384332	total: 6.74s	remaining: 13.9s
327:	learn: 0.0384216	total: 6.76s	remaining: 13.8s
328:	learn: 0.0384010	total: 6.78s	remaining: 13.8s
329:	learn: 0.0384002	total: 6.8s	remaining: 13.8s
330:	learn: 0.0383974	total: 6.81s	remaining: 13.8s
331:	learn: 0.0383922	total: 6.83s	remaining: 13.7s
332:	learn: 0.0383854	total: 6.85s	remaining: 13.7s
333:	learn: 0.0383846	total: 6.88s	remaining: 13.7s
334:	learn: 0.0383675	total: 6.89s	remaining: 13.7s
335:	learn: 0.0383585	total: 6.91s	remaining: 13.7s
336:	learn: 0.0383557	total: 6.93s	remaining: 13.6s
337:	learn: 0.0383422	total: 6.95s	remaining: 13.6s
338:	learn: 0.0383401	total: 6.97s	remaining: 13.6s
339:	learn: 0.0383185	total: 6.99s	remaining: 13.6s
340:	learn: 0.0383078	total: 7.01s	remaining: 13.6s
341:	learn: 0.0383016	total: 7.04s	remaining: 13.5s
342:	learn: 0.0382989	total: 7.05s	remaining: 13.5s
343:	learn: 0.0382984	total: 7.08s	remaining: 13.5s
344:	learn: 0.0382788	total: 7.1s	remaining: 13.5s
345:	learn: 0.0382717	total: 7.12s	remaining: 13.5s
346:	learn: 0.0382681	total: 7.14s	remaining: 13.4s
347:	learn: 0.0382631	total: 7.16s	remaining: 13.4s
348:	learn: 0.0382522	total: 7.18s	remaining: 13.4s
349:	learn: 0.0382444	total: 7.2s	remaining: 13.4s
350:	learn: 0.0382322	total: 7.22s	remaining: 13.3s
351:	learn: 0.0382305	total: 7.24s	remaining: 13.3s
352:	learn: 0.0381959	total: 7.26s	remaining: 13.3s
353:	learn: 0.0381707	total: 7.28s	remaining: 13.3s
354:	learn: 0.0381582	total: 7.3s	remaining: 13.3s
355:	learn: 0.0381310	total: 7.32s	remaining: 13.2s
356:	learn: 0.0381185	total: 7.35s	remaining: 13.2s
357:	learn: 0.0381086	total: 7.37s	remaining: 13.2s
358:	learn: 0.0380968	total: 7.39s	remaining: 13.2s
359:	learn: 0.0380877	total: 7.41s	remaining: 13.2s
360:	learn: 0.0380706	total: 7.43s	remaining: 13.2s
361:	learn: 0.0380652	total: 7.45s	remaining: 13.1s
362:	learn: 0.0380490	total: 7.47s	remaining: 13.1s
363:	learn: 0.0380359	total: 7.49s	remaining: 13.1s
364:	learn: 0.0380292	total: 7.51s	remaining: 13.1s
365:	learn: 0.0380178	total: 7.53s	remaining: 13s
366:	learn: 0.0380044	total: 7.57s	remaining: 13s
367:	learn: 0.0379679	total: 7.61s	remaining: 13.1s
368:	learn: 0.0379591	total: 7.63s	remaining: 13.1s
369:	learn: 0.0379540	total: 7.66s	remaining: 13s
370:	learn: 0.0379451	total: 7.69s	remaining: 13s
371:	learn: 0.0379374	total: 7.71s	remaining: 13s
372:	learn: 0.0379055	total: 7.73s	remaining: 13s
373:	learn: 0.0378907	total: 7.75s	remaining: 13s
374:	learn: 0.0378826	total: 7.77s	remaining: 12.9s
375:	learn: 0.0378535	total: 7.79s	remaining: 12.9s
376:	learn: 0.0378199	total: 7.82s	remaining: 12.9s
377:	learn: 0.0377965	total: 7.87s	remaining: 12.9s
378:	learn: 0.0377820	total: 7.89s	remaining: 12.9s
379:	learn: 0.0377774	total: 7.91s	remaining: 12.9s
380:	learn: 0.0377745	total: 7.93s	remaining: 12.9s
381:	learn: 0.0377492	total: 7.95s	remaining: 12.9s
382:	learn: 0.0377357	total: 7.97s	remaining: 12.8s
383:	learn: 0.0377242	total: 7.99s	remaining: 12.8s
384:	learn: 0.0377219	total: 8.01s	remaining: 12.8s
385:	learn: 0.0377026	total: 8.03s	remaining: 12.8s
386:	learn: 0.0376862	total: 8.05s	remaining: 12.8s
387:	learn: 0.0376649	total: 8.08s	remaining: 12.7s

In [23]:
from sklearn.metrics import brier_score_loss, roc_auc_score, log_loss

testX, testY = X, Y

def evaluate(y, y_hat):
    p = sum(y) / len(y)
    base = [p] * len(y)
    brier = brier_score_loss(y, y_hat)
    print(f"  Brier score: %.5f (%.5f)" % (brier, brier / brier_score_loss(y, base)))
    ll = log_loss(y, y_hat)
    print(f"  log loss score: %.5f (%.5f)" % (ll, ll / log_loss(y, base)))
    print(f"  ROC AUC: %.5f" % roc_auc_score(y, y_hat))

for col in testY.columns:
    Y_hat[col] = [p[1] for p in models[col].predict_proba(testX)]
    print(f"### Y: {col} ###")
    evaluate(testY[col], Y_hat[col])

### Y: scores ###
  Brier score: 0.00614 (0.59181)
  log loss score: 0.02964 (0.50871)
  ROC AUC: 0.93885
### Y: concedes ###
  Brier score: 0.00132 (0.49938)
  log loss score: 0.00716 (0.38869)
  ROC AUC: 0.97353

In [32]:
A = []
for game_id in tqdm.tqdm(games.game_id, "Loading game ids"):
    Ai = pd.read_hdf(spadl_h5, f"actions/game_{game_id}")
    A.append(Ai[["game_id"]])
A = pd.concat(A)
A = A.reset_index(drop=True)

# concatenate action game id rows with predictions and save per game
grouped_predictions = pd.concat([A, Y_hat], axis=1).groupby("game_id")
for k, df in tqdm.tqdm(grouped_predictions, desc="Saving predictions per game"):
    df = df.reset_index(drop=True)
    df[Y_hat.columns].to_hdf(predictions_h5, f"game_{int(k)}")

Loading game ids: 100%|██████████| 64/64 [00:00<00:00, 121.26it/s]
Saving predictions per game: 100%|██████████| 64/64 [00:00<00:00, 68.58it/s]

In [33]:
Y_hat

          scores  concedes
0       0.000259  0.002054
1       0.000718  0.002020
2       0.002524  0.001847
3       0.003820  0.020883
4       0.004918  0.000672
...          ...       ...
128932  0.521835  0.000156
128933  0.161773  0.000193
128934  0.243102  0.000588
128935  0.977680  0.000472
128936  0.003784  0.000140

[128937 rows x 2 columns]

In [34]:
Y

        scores  concedes
0        False     False
1        False     False
2        False     False
3        False     False
4        False     False
...        ...       ...
128932    True     False
128933    True     False
128934    True     False
128935    True     False
128936   False     False

[128937 rows x 2 columns]